version: 2.1
jobs:
  run_unit_tests:
    docker:
        - image: golang:1.-12-alpine
    steps:
     - checkout
     - run:
        name: Run unit tests
        command: go test -v ./...
workflows:
  version: 2
  default:
    jobs:
        - run_unit_tests
