version: 2.1
jobs:
  run_unit_tests:
    docker:
        - image: circleci/golang:1.12
    steps:
     - checkout
     - run:
        name: Run unit tests
        command: go test -v ./...
workflows:
  version: 2
  default:
    jobs:
        - run_unit_tests
