name: Docker Stable Build
on:
  push:
    branches:
      - master
      - stable
jobs:
  docker-build-push:
    uses: docker/build-push-action@v1
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      repository: bbriggs/bitbot
      tags: stable
      add_git_labels: true
---
name: Docker Release Build
on:
  release:
    types:
      - created
      - published
jobs:
  docker-build-push:
    uses: docker/build-push-action@v1
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      repository: bbriggs/bitbot
      tag_with_ref: true
      add_git_labels: true
