name: Docker Stable Build
on:
  push:
    branches:
      - stable
      - master
jobs:
  build:
    name: Stable Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bitbot
          tags: stable
          push: true
          add_git_labels: true

