name: Docker Stable Build
on:
  push:
    branches:
      - stable
      - master
jobs:
  build:
    steps:
      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bitbot
          tags: stable
          push: true
          add_git_labels: true
---
name: Docker Release Build
on:
  release:
    types:
      - created
      - published
jobs:
  build:
    steps:
      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bitbot
          add_git_labels: true
          push: true
