name: Docker Build and Push

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches:
      - 'dev'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Set current epoch time as env variable
        run: echo "NOW=$(date +%s)" >> $GITHUB_ENV
      -
        name: Echo current date
        run: echo $NOW

      -
        name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: dkr.fraq.dev/fraq/bitbot
          tags: |
            type=edge
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=sha-,suffix=-${NOW},format=short
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        if: github.event_name != 'pull_request'
        with:
          registry: dkr.fraq.dev
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

